export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL'

export const LIST_IMAGE_REQUEST = 'LIST_IMAGE_REQUEST'
export const LIST_IMAGE_SUCCESS = 'LIST_IMAGE_SUCCESS'
export const LIST_IMAGE_FAIL = 'LIST_IMAGE_FAIL'

export const INCREMENT_IMAGE_COUNT_REQUEST = 'INCREMENT_IMAGE_COUNT_REQUEST'
export const INCREMENT_IMAGE_COUNT_SUCCESS = 'INCREMENT_IMAGE_COUNT_SUCCESS'
export const INCREMENT_IMAGE_COUNT_FAIL = 'INCREMENT_IMAGE_COUNT_FAIL'
